import mongoose from "mongoose";

const baseEstablishmentSchema = mongoose.Schema({
  key: Object,
  title: Object,
  updatedAt: Object,
  noFinesset: Object,
  capacity: Object,
  legal_status: Object,
  isViaTrajectoire: Object,
  IsEHPAD: Object,
  IsEHPA: Object,
  IsESLD: Object,
  IsRA: Object,
  IsAJA: Object,
  IsHCOMPL: Object,
  IsHTEMPO: Object,
  IsACC_JOUR: Object,
  IsACC_NUIT: Object,
  IsHAB_AIDE_SOC: Object,
  IsCONV_APL: Object,
  IsALZH: Object,
  IsUHR: Object,
  IsPASA: Object,
  IsPUV: Object,
  IsF1: Object,
  IsF1Bis: Object,
  IsF2: Object,
  cerfa: Object,
  prixMin: Object,
  coordinates_id: Object,
  coordinatestitle: Object,
  coordinatesisPublished: Object,
  coordinatescreatedAt: Object,
  coordinatesupdatedAt: Object,
  coordinatesstreet: Object,
  coordinatespostcode: Object,
  coordinatesdeptcode: Object,
  coordinatesdeptname: Object,
  coordinatescity: Object,
  coordinatesphone: Object,
  coordinatesemailContact: Object,
  coordinatesgestionnaire: Object,
  coordinateswebsite: Object,
  coordinateslatitude: Object,
  coordinateslongitude: Object,
  ehpadPrice_id: Object,
  ehpadPriceupdatedAt: Object,
  ehpadPriceprixHebPermCs: Object,
  ehpadPriceprixHebPermCd: Object,
  ehpadPriceprixHebPermCsa: Object,
  ehpadPriceprixHebPermCda: Object,
  ehpadPriceprixHebTempCs: Object,
  ehpadPriceprixHebTempCd: Object,
  ehpadPriceprixHebTempCsa: Object,
  ehpadPriceprixHebTempCda: Object,
  ehpadPricetarifHebJour: Object,
  ehpadPricetarifGir12: Object,
  ehpadPricetarifGir34: Object,
  ehpadPricetarifGir56: Object,
  ehpadPriceautrePrestation: Object,
  ehpadPriceautreTarifPrest: Object,
  raPrice_id: Object,
  raPriceupdatedAt: Object,
  raPricePrixF1: Object,
  raPricePrixF1ASH: Object,
  raPricePrixF1Bis: Object,
  raPricePrixF1BisASH: Object,
  raPricePrixF2: Object,
  raPricePrixF2ASH: Object,
  raPriceautreTarifPrest: Object,
  raPriceprestObligatoire: Object,
  raPrice: Object,
});

const BaseEstablishment = mongoose.model("BaseEstablishment",baseEstablishmentSchema );
export default BaseEstablishment;

const postSchema = mongoose.Schema({
    title: String,
    message: String,
    name: String,
    creator: String,
    tags: [String],
    selectedFile: String,
    likes: {
      //+15703619588
      type: [String],
      default: [],
    },
    comments: { type: [String], default: [] },
    createdAt: {
      type: Date,
      default: new Date(),
    },
  });